export var products = [
  {
    pid: 2,
    pname: 'Mobile Phones',
    vendor: 'Company',
    mrp: 3000,
    batchno: 1,
    batchdate: new Date(),
    quantity: 3,
    status: 'approved',
  },
  {
    pid: 3,
    pname: 'Laptop',
    vendor: 'Tech Co',
    mrp: 1500,
    batchno: 2,
    batchdate: new Date(),
    quantity: 5,
    status: 'approved',
  },
  {
    pid: 4,
    pname: 'Television',
    vendor: 'Electronics Inc',
    mrp: 2500,
    batchno: 3,
    batchdate: new Date(),
    quantity: 2,
    status: 'approved',
  },
  {
    pid: 5,
    pname: 'Headphones',
    vendor: 'AudioTech',
    mrp: 500,
    batchno: 4,
    batchdate: new Date(),
    quantity: 10,
    status: 'approved',
  },
  {
    pid: 1,
    pname: 'Electric Fan',
    vendor: 'Company',
    mrp: 1200,
    batchno: 1,
    batchdate: new Date(),
    quantity: 3,
    status: 'pending',
  },
  // {
  //   pid: 6,
  //   pname: 'Tablet',
  //   vendor: 'Tech Gadgets',
  //   mrp: 800,
  //   batchno: 5,
  //   batchdate: new Date(),
  //   quantity: 6,
  //   status: 'approved',
  // },
  // {
  //   pid: 7,
  //   pname: 'Smartwatch',
  //   vendor: 'Wearables Inc',
  //   mrp: 350,
  //   batchno: 6,
  //   batchdate: new Date(),
  //   quantity: 15,
  //   status: 'approved',
  // },
  // {
  //   pid: 8,
  //   pname: 'Blender',
  //   vendor: 'Kitchen Essentials',
  //   mrp: 60,
  //   batchno: 7,
  //   batchdate: new Date(),
  //   quantity: 12,
  //   status: 'approved',
  // },
];
